# Generated by Django 5.0.1 on 2025-01-04 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_rename_comments_comment_post_delete_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='post', to='network.comment'),
        ),
    ]
