# Generated by Django 5.0.1 on 2025-01-05 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_post_shares'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comment_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='comments',
            field=models.ManyToManyField(blank=0, related_name='post', to='network.comment'),
        ),
    ]
