# Generated by Django 5.0.1 on 2025-01-06 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_rename_likes_post_like_count_post_like_following'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comments',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
